---
title: "Exercise 4 Summary Table"
output: html_document
date: "2025-03-11"
---

```{r}
library(pacman)
p_load(tidyverse, tidycensus, ggplot2, gtsummary,
       kableExtra, flextable, officer, survey, cardx)
CA_pums_select <- read_csv("CA_pums_recoded.csv") %>%
  select(AGEP, HINCP, COW_label, LANX_label, SEX_label,
           NATIVITY_label, RAC1P_label, SCHL_label, PWGTP)
design <- svydesign(id = ~1, weights = ~PWGTP, data = CA_pums_select)
```

```{r}

sumtable <- design %>%
  tbl_svysummary(
    include = c(AGEP, HINCP, COW_label, LANX_label, SEX_label,
           NATIVITY_label, RAC1P_label, SCHL_label),
    statistic = list(
      all_continuous() ~ "{mean} ({sd})",
      all_categorical() ~ "{n}/{N} ({p}%)"
    ),
    digits = list(
      all_continuous() ~ 1,
      all_categorical() ~ 1
    ),
    label = list(
      AGEP ~ "Age",
      HINCP ~ "Household Income",
      COW_label ~ "Class of worker",
      LANX_label ~ "Non-English language spoken at home",
      SEX_label ~ "Sex",
      NATIVITY_label ~ "Nativity",
      RAC1P_label ~ "Race Group",
      SCHL_label ~ "Schooling"
    )
  ) %>%
  modify_caption("Weighted Summary Statistics for 2018 PUMS Data") %>%
  bold_labels()


```
